### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by singinglia** [RitchieLab/GWAS-QC#13]
I am trying to follow your tutorial and on step 11 in the pre-imputation section, it says that I need the file "~/group/projects/PMBB/QC_Imputation/scripts/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta". I can't find any other reference to this file in the tutorial. Is any homo sapien assembly of 38 sufficient to use here?

Thank you for setting up such a thorough tutorial.

**Comment by alldayscientess** [comment]
Hi @singinglia thank you so much for trying out our tutorial and for your kind words. I am sorry about the missing file. You can use this file instead.

`wget https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta`

I will update the github soon with this fix.

**Comment by alldayscientess** [comment]
Oh you will also need this file: https://storage.googleapis.com/genomics-public-data/resources/broad/hg38/v0/Homo_sapiens_assembly38.fasta.fai

**Comment by alldayscientess** [comment]
I'm resolving this, let me know if you have additional issues.
